name: pull-request

on: 
  pull_request:

jobs:
  test-unix:
    strategy:
      fail-fast: false
      matrix:
        platform:
        - ubuntu
        - macOS
        - windows
        go:
        - 1.19.x
        - 1.20.x
        - 1.21.x
    name: '${{ matrix.platform }} | ${{ matrix.go }}'
    runs-on: ${{ matrix.platform }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Test
        run: |
          go test ./...
          go test -race ./...